import type { Weapon } from "./warframe-data";

export const COMPANION_WEAPONS: Weapon[] = [
  {
    id: "verglas",
    name: "Verglas",
    type: "primary",
    isPrime: false,
    mastery: 0,
    damage: 22,
    critChance: 0.22,
    critMultiplier: 2.2,
    statusChance: 0.22,
    fireRate: 15,
    rarity: "common",
    description: "Arme de tir robotique (Sentinelle Nautilus). Inflige des dégâts de Glace continus.",
    weaponClass: "Sentinel Weapon",
    trigger: "Continuous",
    accuracy: 100,
    magazineSize: 100,
    reloadTime: 1.5,
    disposition: 1.0,
    damageTypes: { cold: 22 },
    polarities: ["vazarin", "madurai"]
  },
  {
    id: "cryotra",
    name: "Cryotra",
    type: "primary",
    isPrime: false,
    mastery: 0,
    damage: 18,
    critChance: 0.15,
    critMultiplier: 2.0,
    statusChance: 0.25,
    fireRate: 12,
    rarity: "common",
    description: "Arme de tir robotique (MOA / Sentinelle). Fait feu de cristaux givrés.",
    weaponClass: "Sentinel Weapon",
    trigger: "Beam",
    accuracy: 100,
    magazineSize: 50,
    reloadTime: 2.0,
    disposition: 1.0,
    damageTypes: { cold: 18 },
    polarities: ["vazarin"]
  },
  {
    id: "vulcax",
    name: "Vulcax",
    type: "primary",
    isPrime: false,
    mastery: 0,
    damage: 130,
    critChance: 0.30,
    critMultiplier: 2.5,
    statusChance: 0.15,
    fireRate: 1.5,
    rarity: "common",
    description: "Fusil de précision robotique pour Sentinelles et MOAs. Tir perçant à longue portée.",
    weaponClass: "Sentinel Weapon",
    trigger: "Sniper",
    accuracy: 100,
    magazineSize: 6,
    reloadTime: 2.5,
    disposition: 1.0,
    damageTypes: { puncture: 85, heat: 45 },
    polarities: ["madurai"]
  },
  {
    id: "helstrum",
    name: "Helstrum",
    type: "primary",
    isPrime: false,
    mastery: 0,
    damage: 35,
    critChance: 0.10,
    critMultiplier: 1.8,
    statusChance: 0.40,
    fireRate: 3.33,
    rarity: "common",
    description: "Lance-roquettes multiple robotique. Tire des micro-missiles à guidage de statut.",
    weaponClass: "Sentinel Weapon",
    trigger: "Burst",
    accuracy: 75,
    magazineSize: 30,
    reloadTime: 2.0,
    disposition: 1.0,
    damageTypes: { blast: 35 },
    polarities: ["madurai", "naramon"]
  },
  {
    id: "tazicor",
    name: "Tazicor",
    type: "primary",
    isPrime: false,
    mastery: 0,
    damage: 28,
    critChance: 0.18,
    critMultiplier: 2.0,
    statusChance: 0.20,
    fireRate: 8,
    rarity: "common",
    description: "Fusil laser robotique à rafales électriques.",
    weaponClass: "Sentinel Weapon",
    trigger: "Burst",
    accuracy: 90,
    magazineSize: 40,
    reloadTime: 1.8,
    disposition: 1.0,
    damageTypes: { electricity: 28 },
    polarities: ["vazarin"]
  },
  {
    id: "deconstructor",
    name: "Deconstructor",
    type: "secondary",
    isPrime: false,
    mastery: 0,
    damage: 100,
    critChance: 0.15,
    critMultiplier: 2.0,
    statusChance: 0.15,
    fireRate: 1.2,
    rarity: "common",
    description: "Arme de jet robotique de Diriga. Se détache pour frapper les ennemis en mêlée/jet.",
    weaponClass: "Sentinel Weapon",
    trigger: "Thrown",
    accuracy: 100,
    magazineSize: 1,
    reloadTime: 1.0,
    disposition: 1.0,
    damageTypes: { impact: 40, puncture: 20, slash: 40 },
    polarities: ["naramon", "madurai"]
  },
  {
    id: "deth_machine_rifle",
    name: "Deth Machine Rifle",
    type: "primary",
    isPrime: false,
    mastery: 0,
    damage: 20,
    critChance: 0.10,
    critMultiplier: 1.5,
    statusChance: 0.10,
    fireRate: 10,
    rarity: "common",
    description: "Mitrailleuse robotique lourde pour Dethcube.",
    weaponClass: "Sentinel Weapon",
    trigger: "Auto",
    accuracy: 80,
    magazineSize: 100,
    reloadTime: 2.0,
    disposition: 1.0,
    damageTypes: { impact: 5, puncture: 5, slash: 10 },
    polarities: ["madurai"]
  },
  {
    id: "burst_laser",
    name: "Burst Laser",
    type: "primary",
    isPrime: false,
    mastery: 0,
    damage: 25,
    critChance: 0.10,
    critMultiplier: 1.5,
    statusChance: 0.05,
    fireRate: 5,
    rarity: "common",
    description: "Pistolet laser robotique à rafale courte.",
    weaponClass: "Sentinel Weapon",
    trigger: "Burst",
    accuracy: 85,
    magazineSize: 15,
    reloadTime: 2.0,
    disposition: 1.0,
    damageTypes: { puncture: 15, heat: 10 },
    polarities: ["vazarin"]
  },
  {
    id: "artax",
    name: "Artax",
    type: "primary",
    isPrime: false,
    mastery: 0,
    damage: 10,
    critChance: 0.05,
    critMultiplier: 1.5,
    statusChance: 0.50,
    fireRate: 8,
    rarity: "common",
    description: "Laser de focalisation gelant les cibles à l'impact.",
    weaponClass: "Sentinel Weapon",
    trigger: "Continuous",
    accuracy: 100,
    magazineSize: 50,
    reloadTime: 2.0,
    disposition: 1.0,
    damageTypes: { cold: 10 },
    polarities: ["vazarin"]
  },
  {
    id: "vulklok",
    name: "Vulklok",
    type: "primary",
    isPrime: false,
    mastery: 0,
    damage: 120,
    critChance: 0.25,
    critMultiplier: 2.5,
    statusChance: 0.10,
    fireRate: 1.0,
    rarity: "common",
    description: "Fusil laser lourd à longue portée de Shade.",
    weaponClass: "Sentinel Weapon",
    trigger: "Sniper",
    accuracy: 100,
    magazineSize: 5,
    reloadTime: 3.0,
    disposition: 1.0,
    damageTypes: { puncture: 120 },
    polarities: ["madurai"]
  },
  {
    id: "sweeper",
    name: "Sweeper",
    type: "primary",
    isPrime: false,
    mastery: 0,
    damage: 100,
    critChance: 0.10,
    critMultiplier: 1.5,
    statusChance: 0.10,
    fireRate: 1.67,
    rarity: "common",
    description: "Fusil à pompe robotique pour Carrier.",
    weaponClass: "Sentinel Weapon",
    trigger: "Semi-Auto",
    accuracy: 50,
    magazineSize: 10,
    reloadTime: 2.0,
    disposition: 1.0,
    damageTypes: { impact: 30, puncture: 20, slash: 50 },
    polarities: ["madurai", "vazarin"]
  },
  {
    id: "akaten",
    name: "Akaten",
    type: "melee",
    isPrime: false,
    mastery: 0,
    damage: 120,
    critChance: 0.20,
    critMultiplier: 2.0,
    statusChance: 0.20,
    fireRate: 1.1,
    rarity: "common",
    description: "Arme de mêlée robotique pour les Hounds (Sororité Corpus).",
    weaponClass: "Hound Weapon",
    trigger: "Melee",
    accuracy: 100,
    magazineSize: 0,
    reloadTime: 0,
    disposition: 1.0,
    damageTypes: { slash: 90, puncture: 30 },
    polarities: ["naramon", "madurai"]
  },
  {
    id: "batoten",
    name: "Batoten",
    type: "melee",
    isPrime: false,
    mastery: 0,
    damage: 120,
    critChance: 0.15,
    critMultiplier: 2.0,
    statusChance: 0.25,
    fireRate: 1.0,
    rarity: "common",
    description: "Arme de mêlée lourde robotique pour les Hounds.",
    weaponClass: "Hound Weapon",
    trigger: "Melee",
    accuracy: 100,
    magazineSize: 0,
    reloadTime: 0,
    disposition: 1.0,
    damageTypes: { impact: 80, electricity: 40 },
    polarities: ["naramon", "vazarin"]
  },
  {
    id: "lacerten",
    name: "Lacerten",
    type: "melee",
    isPrime: false,
    mastery: 0,
    damage: 120,
    critChance: 0.22,
    critMultiplier: 2.2,
    statusChance: 0.22,
    fireRate: 1.2,
    rarity: "common",
    description: "Lame robotique de mêlée pour les Hounds.",
    weaponClass: "Hound Weapon",
    trigger: "Melee",
    accuracy: 100,
    magazineSize: 0,
    reloadTime: 0,
    disposition: 1.0,
    damageTypes: { slash: 70, cold: 50 },
    polarities: ["naramon"]
  },
  {
    id: "kubrow_claws",
    name: "Kubrow Claws",
    type: "melee",
    isPrime: false,
    mastery: 0,
    damage: 150,
    critChance: 0.25,
    critMultiplier: 2.0,
    statusChance: 0.10,
    fireRate: 1.2,
    rarity: "common",
    description: "Griffes naturelles des Kubrows. Modifiables avec des mods de posture et de mêlée de bête.",
    weaponClass: "Beast Claws",
    trigger: "Melee",
    accuracy: 100,
    magazineSize: 0,
    reloadTime: 0,
    disposition: 1.0,
    damageTypes: { slash: 120, puncture: 30 },
    polarities: ["penjaga", "naramon"]
  },
  {
    id: "kavat_claws",
    name: "Kavat Claws",
    type: "melee",
    isPrime: false,
    mastery: 0,
    damage: 130,
    critChance: 0.35,
    critMultiplier: 2.5,
    statusChance: 0.20,
    fireRate: 1.3,
    rarity: "common",
    description: "Griffes acérées des Kavats. Permet des dégâts critiques et de taillade élevés.",
    weaponClass: "Beast Claws",
    trigger: "Melee",
    accuracy: 100,
    magazineSize: 0,
    reloadTime: 0,
    disposition: 1.0,
    damageTypes: { slash: 110, puncture: 20 },
    polarities: ["penjaga", "madurai"]
  },
  {
    id: "vulpaphyla_claws",
    name: "Vulpaphyla Claws",
    type: "melee",
    isPrime: false,
    mastery: 0,
    damage: 140,
    critChance: 0.20,
    critMultiplier: 2.0,
    statusChance: 0.30,
    fireRate: 1.2,
    rarity: "common",
    description: "Griffes de Vulpaphyla infligeant de violents dégâts de statut.",
    weaponClass: "Beast Claws",
    trigger: "Melee",
    accuracy: 100,
    magazineSize: 0,
    reloadTime: 0,
    disposition: 1.0,
    damageTypes: { slash: 100, toxin: 40 },
    polarities: ["penjaga", "vazarin"]
  },
  {
    id: "predasite_claws",
    name: "Predasite Claws",
    type: "melee",
    isPrime: false,
    mastery: 0,
    damage: 160,
    critChance: 0.22,
    critMultiplier: 2.2,
    statusChance: 0.15,
    fireRate: 1.1,
    rarity: "common",
    description: "Griffes massives de Prédasite orientées sur la force brute.",
    weaponClass: "Beast Claws",
    trigger: "Melee",
    accuracy: 100,
    magazineSize: 0,
    reloadTime: 0,
    disposition: 1.0,
    damageTypes: { puncture: 100, slash: 60 },
    polarities: ["penjaga", "madurai"]
  }
];
