// API client for Cephalon‑Wodan service.
// Provides helper functions to fetch the enriched datasets exposed by the
// Express server running on cephalon‑wodan-production.up.railway.app.

export const API_BASE:
  string =
    // Use the environment variable if provided, otherwise fallback to the
    // production deployment of Cephalon‑Wodan.
    import.meta.env.VITE_CEPHALON_API_BASE ||
    'https://cephalon-wodan-production.up.railway.app';

async function getJSON<T>(path: string): Promise<T> {
  const url = path.startsWith('http') ? path : `${API_BASE}${path}`;
  const res = await fetch(url, { cache: 'no-store' });
  if (!res.ok) {
    throw new Error(`Failed to fetch ${url}: ${res.status} ${res.statusText}`);
  }
  return res.json() as Promise<T>;
}

// Lightweight type declarations for API responses. These mirror the
// structures generated by the tools scripts but omit unneeded fields.
export interface ApiWarframe {
  id?: string;
  uniqueName?: string;
  name?: string;
  displayName?: string;
  baseStats?: any;
  baseStatsRank30?: any;
  polarities?: string[];
}

export interface ApiWeapon {
  id?: string;
  name: string;
  type?: string;
  totalDamage?: number;
  imageName?: string;
}

export interface ApiMod {
  id?: string;
  name?: string;
  displayName?: string;
  polarity?: string;
  rarity?: string;
  compat?: string;
  description?: string;
  baseDrain?: number;
  drain?: number;
}

export interface ApiArcane {
  id?: string;
  name?: string;
  rarity?: string;
  type?: string;
  description?: string;
}

export interface ApiArchonShardMap {
  [color: string]: { upgrades: string[] };
}

export interface WorldstateAggregated {
  [key: string]: any;
}

// Endpoints to fetch data. Each returns a Promise with the parsed JSON.
export const api = {
  warframes: () => getJSON<ApiWarframe[]>('/warframes'),
  weapons: () => getJSON<ApiWeapon[]>('/weapons'),
  mods: () => getJSON<ApiMod[]>('/mods'),
  arcanes: () => getJSON<ApiArcane[]>('/arcanes'),
  shards: () => getJSON<ApiArchonShardMap>('/archonshards'),
  worldstate: (platform: 'pc' | 'ps4' | 'xbox' | 'swi' = 'pc') =>
    getJSON<WorldstateAggregated>(`/api/${platform}`),
  worldstateSection: (
    platform: 'pc' | 'ps4' | 'xbox' | 'swi',
    section: string
  ) => getJSON<any>(`/api/${platform}/${encodeURIComponent(section)}`),
};