name: API – Worldstate

on:
  schedule:
    - cron: "*/5 * * * *"         # toutes les 5 minutes
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: api-worldstate
  cancel-in-progress: false

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install jq
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Prepare folders
        run: |
          set -e
          mkdir -p api/v1/worldstate/{pc,ps4,xb1,swi}
          echo "Folders ready."

      - name: Download snapshots (pc/ps4/xb1/swi · en/fr) with logs
        shell: bash
        run: |
          set -euo pipefail
          UA="wf-hub/1.0 (+github.com/Cephalon-Wodan/Cephalon-Wodan)"
          wrote=0

          for lang in en fr; do
            for plat in pc ps4 xb1 swi; do
              url="https://api.warframestat.us/${plat}?language=${lang}"
              dest="api/v1/worldstate/${plat}/${lang}.json"
              tmp="${dest}.tmp"
              echo "→ GET $url"
              code=$(curl -L -H "User-Agent: $UA" -w "%{http_code}" -sS -o "$tmp" "$url" || true)
              echo "  HTTP $code"
              if [[ "$code" =~ ^2 ]]; then
                # Valide + compresse le JSON en ligne unique
                if jq -e -c . "$tmp" > "$dest"; then
                  sz=$(wc -c < "$dest")
                  echo "  ✓ wrote $dest ($sz bytes)"
                  wrote=$((wrote+1))
                else
                  echo "  ✗ jq validation failed for $url"
                  rm -f "$tmp"
                fi
              else
                echo "  ✗ download failed for $url"
              fi
              rm -f "$tmp"
            done
          done

          echo "================ Summary ================"
          ls -lh api/v1/worldstate/*/*.json 2>/dev/null || true
          echo "Files written: $wrote"
          # Si rien n'a été écrit, échoue explicitement pour le voir dans les logs
          if [ "$wrote" -eq 0 ]; then
            echo "No snapshot written. Check HTTP codes above (rate limit ? network ?)."
            exit 1
          fi

      - name: Commit & push changes
        shell: bash
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A api/v1/worldstate || true
          if git diff --cached --quiet; then
            echo "Nothing to commit."
            exit 0
          fi
          git commit -m "worldstate: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          git pull --rebase || true
          git push
