name: API – Export mirror

on:
  schedule:
    - cron: "0 */6 * * *"   # toutes les 6h
  workflow_dispatch:

permissions:
  contents: write

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Mirror data/Export*.json -> api/v1/export
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p api/v1/export
          cp -f data/Export*.json api/v1/export/ 2>/dev/null || true
          # index
          ls -1 api/v1/export/Export*.json | sed 's|.*/||' | jq -R . | jq -s '{files: ., updatedAt: (now|todate)}' > api/v1/export/index.json

      - name: Commit & push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --quiet && echo "No changes" && exit 0
          git commit -m "export mirror: update"
          git push
