name: API – Worldstate

on:
  schedule:
    - cron: "*/5 * * * *"       # toutes les 5 minutes
  workflow_dispatch:

permissions:
  contents: write               # nécessaire pour git push

concurrency:
  group: api-worldstate
  cancel-in-progress: false

jobs:
  fetch:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install jq
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Prepare folders
        run: |
          set -e
          mkdir -p api/v1/worldstate/{pc,ps4,xb1,swi}

      - name: Download snapshots (pc/ps4/xb1/swi · en/fr) with debug
        shell: bash
        run: |
          set -Eeuo pipefail
          UA="Cephalon-Wodan-Worldstate/1.0 (+https://cephalonwodan.github.io)"
          wrote=0

          for lang in en fr; do
            for plat in pc ps4 xb1 swi; do
              url="https://api.warframestat.us/${plat}?language=${lang}"
              dest="api/v1/worldstate/${plat}/${lang}.json"
              tmp="${dest}.tmp"

              echo "::group::GET $url"
              http=$(curl -sS -L \
                         --retry 5 --retry-delay 2 --retry-all-errors \
                         --connect-timeout 15 --max-time 60 \
                         -H "User-Agent: $UA" \
                         -H "Accept: application/json" \
                         -w "%{http_code}" -o "$tmp" "$url" || true)
              echo "HTTP: $http"

              if [[ "$http" =~ ^2 ]]; then
                if jq -e -c . "$tmp" > "$dest"; then
                  sz=$(wc -c < "$dest")
                  echo "✓ wrote $dest ($sz bytes)"
                  wrote=$((wrote+1))
                else
                  echo "✗ Invalid JSON. First 200 bytes:"
                  head -c 200 "$tmp" | sed 's/[^[:print:]]//g'; echo
                fi
              else
                echo "✗ Download failed. First 200 bytes:"
                head -c 200 "$tmp" | sed 's/[^[:print:]]//g'; echo
              fi

              rm -f "$tmp"
              echo "::endgroup::"
            done
          done

          echo "================ Summary ================"
          ls -l api/v1/worldstate/*/*.json 2>/dev/null || true
          echo "Files written: $wrote"
          if [ "$wrote" -eq 0 ]; then
            echo "No snapshot written -> failing to surface the problem."
            exit 1
          fi

      - name: Commit & push changes
        shell: bash
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A api/v1/worldstate || true
          if git diff --cached --quiet; then
            echo "Nothing to commit."
            exit 0
          fi
          git commit -m "worldstate: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          git pull --rebase || true
          git push
