name: API – Worldstate

on:
  schedule:
    - cron: "*/5 * * * *"   # toutes les 5 minutes
  workflow_dispatch:

permissions:
  contents: write   # indispensable pour commit & push

concurrency:
  group: worldstate
  cancel-in-progress: true

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download snapshots
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p api/v1/worldstate
          for plat in pc ps4 xb1 swi; do
            mkdir -p "api/v1/worldstate/$plat"
            for lang in en fr; do
              url="https://api.warframestat.us/${plat}?language=${lang}"
              out="api/v1/worldstate/$plat/${lang}.json"
              echo "GET $url -> $out"
              curl -fsSL "$url" -o "$out"
            done
          done
          # petit index
          jq -n '
            { platforms: ["pc","ps4","xb1","swi"],
              languages: ["en","fr"],
              updatedAt: (now|todate) }' > api/v1/worldstate/index.json

      - name: Commit & push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --quiet && echo "No changes" && exit 0
          git commit -m "worldstate: update"
          git push
