name: API – Worldstate

on:
  schedule:
    - cron: "*/5 * * * *"   # toutes les 5 minutes
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: api-worldstate
  cancel-in-progress: false

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Install jq
        run: sudo apt-get update -y && sudo apt-get install -y jq

      - name: Fetch Warframe worldstate (pc/ps4/xb1/swi · en/fr)
        shell: bash
        run: |
          set -euo pipefail
          UA="wf-hub/1.0 (+github.com/Cephalon-Wodan/Cephalon-Wodan)"
          mkdir -p api/v1/worldstate/{pc,ps4,xb1,swi}
          ok=0
          for lang in en fr; do
            for plat in pc ps4 xb1 swi; do
              url="https://api.warframestat.us/${plat}?language=${lang}"
              dest="api/v1/worldstate/${plat}/${lang}.json"
              echo "→ $url"
              # retry + fail if non-2xx; never write an empty placeholder
              curl -fsSL --retry 3 --retry-delay 2 -H "User-Agent: $UA" "$url" \
                | jq -e -c . > "${dest}"
              ok=1
            done
          done
          # print a quick summary
          echo "===== sizes ====="
          find api/v1/worldstate -type f -name '*.json' -exec ls -lh {} \;

      - name: Commit & push
        if: always()
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A api/v1/worldstate || true
          if git diff --cached --quiet; then
            echo "Nothing to commit."
            exit 0
          fi
          git commit -m "worldstate: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          git pull --rebase || true
          git push
