name: API – Worldstate

on:
  schedule:
    - cron: "*/5 * * * *"   # toutes les 5 minutes
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: api-worldstate
  cancel-in-progress: false

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install jq
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Fetch Warframe worldstate (pc/ps4/xb1/swi · en/fr)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p api/v1/worldstate/{pc,ps4,xb1,swi}
          for lang in en fr; do
            for plat in pc ps4 xb1 swi; do
              url="https://api.warframestat.us/${plat}?language=${lang}"
              dest="api/v1/worldstate/${plat}/${lang}.json"
              echo "→ $url"
              if curl -fsSL -H "Accept: application/json" -H "User-Agent: gh-actions/1.0" "$url" -o "${dest}.tmp"; then
                if [ -s "${dest}.tmp" ] && jq -e . "${dest}.tmp" > "${dest}.new"; then
                  # refuse de publier {} (longueur 0)
                  if [ "$(jq 'length' "${dest}.new")" -gt 0 ]; then
                    mv "${dest}.new" "${dest}"
                    echo "✅ saved ${dest}"
                  else
                    echo "⚠️  Snapshot vide pour ${plat}/${lang}, on conserve l’ancienne copie si elle existe."
                    rm -f "${dest}.new"
                    [ -f "${dest}" ] || printf "{}" > "${dest}"
                  fi
                fi
                rm -f "${dest}.tmp"
              else
                echo "❌ curl a échoué pour ${url}"
                [ -f "${dest}" ] || printf "{}" > "${dest}"
              fi
            done
          done

      - name: Commit & push
        shell: bash
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add api/v1/worldstate || true
          git diff --cached --quiet && { echo "Rien à committer."; exit 0; }
          git commit -m "worldstate: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          git pull --rebase || true
          git push
