name: Enrich weapons (merge WFStat + complements)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "12 4 * * *"
  push:
    paths:
      - "tools/enrich_weapons.js"
      - ".github/workflows/enrich-weapons.yml"
      - "!data/enriched_weapons.json"
      - "!data/enriched_weapons.csv"
      - "!data/enriched_weapons_report.json"
  workflow_call: {}

permissions:
  contents: write

concurrency:
  group: build-weapons
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Ensure data dir
        run: mkdir -p data

      - name: Fetch WFStat weapons (EN)
        run: |
          curl -fsSL "https://api.warframestat.us/weapons?language=en" \
            -H "Accept: application/json" \
            -o data/wfstat_weapons.json
          test -s data/wfstat_weapons.json

      - name: Run enrich_weapons.js
        run: node tools/enrich_weapons.js

      - name: Preview outputs
        run: |
          head -n 40 data/enriched_weapons.json || true
          wc -l data/enriched_weapons.csv || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: enriched-weapons
          path: |
            data/enriched_weapons.json
            data/enriched_weapons.csv
            data/enriched_weapons_report.json

      - name: Commit outputs if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/enriched_weapons.json data/enriched_weapons.csv data/enriched_weapons_report.json
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "chore(weapons): update enriched weapons ($(date -u +'%Y-%m-%d %H:%M:%S UTC'))"
            git push
          fi

  # Permet à l'orchestrateur de l'appeler
  expose:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - run: echo "workflow_call enabled"
