name: Enrich Weapons

on:
  workflow_dispatch: {}
  workflow_call: {}
  push:
    paths:
      - "data/overframe/**"
      - "data/wfcd_items/**"
      - "data/ExportWeapons_en.json"
      - "tools/enrich_weapons.js"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run enrich_weapons
        run: node tools/enrich_weapons.js

      - name: Commit enriched files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/enriched_weapons.json data/enriched_weapons_report.json
          git diff --cached --quiet && echo "No changes." || git commit -m "chore(data): update enriched_weapons"
      - name: Push
        if: always()
        run: |
          git push || true
