name: Orchestrator (full data pipeline)

on:
  workflow_dispatch:
  schedule:
    - cron: "5 */6 * * *"

permissions:
  contents: write

# Empêche deux exécutions de la pipeline de se chevaucher
concurrency:
  group: pipeline-orchestrator
  cancel-in-progress: true

jobs:
  # 1) Exports officiels DE (PublicExport)
  update_exports:
    name: 1) Update DE Public Export
    uses: ./.github/workflows/update-exports.yml
    secrets: inherit
    permissions:
      contents: write

  # 2) Jeux de données WFCD (après exports)
  update_wfcd:
    name: 2) Update WFCD datasets
    needs: [update_exports]
    uses: ./.github/workflows/update-wfcd.yml
    secrets: inherit
    permissions:
      contents: write

  # 3) Overframe (pages + chunks)
  scrape_overframe:
    name: 3) Scrape Overframe (pages & chunks)
    needs: [update_wfcd]
    uses: ./.github/workflows/scrape-overframe.yml
    secrets: inherit
    permissions:
      contents: write

  # 4) WFStat weapons (après Overframe)
  fetch_wfstat_weapons:
    name: 4) Fetch WFStat weapons
    needs: [scrape_overframe]
    uses: ./.github/workflows/fetch-wfstat-weapons.yml
    secrets: inherit
    permissions:
      contents: write

  # 5) Enrich mods (après WFStat)
  enrich_mods:
    name: 5) Build enriched_mods
    needs: [fetch_wfstat_weapons]
    uses: ./.github/workflows/enrich-mods.yml
    secrets: inherit
    permissions:
      contents: write

  # 6) Enrich weapons (après enrich_mods)
  enrich_weapons:
    name: 6) Build enriched_weapons
    needs: [enrich_mods]
    uses: ./.github/workflows/enrich-weapons.yml   # <- tu as bien renommé le fichier
    secrets: inherit
    permissions:
      contents: write

  # 7) Build reliques (après enrich_weapons)
  build_relics:
    name: 7) Build enriched_relics
    needs: [enrich_weapons]
    uses: ./.github/workflows/build-relics.yml
    secrets: inherit
    permissions:
      contents: write

  # 8) Merge Warframes final (dernier)
  build_merged_warframes:
    name: 8) Build merged_warframe.json
    needs: [build_relics]
    uses: ./.github/workflows/build-merged-warfames.yml
    secrets: inherit
    permissions:
      contents: write
