name: Orchestrator (full data pipeline)

on:
  workflow_dispatch:
  schedule:
    - cron: "5 */6 * * *"  # cadence globale (ajuste si besoin)

permissions:
  contents: write

concurrency:
  group: pipeline-orchestrator
  cancel-in-progress: false

jobs:
  # 1) Exports officiels DE (PublicExport)
  update_exports:
    name: 1) Update DE Public Export
    uses: ./.github/workflows/update-exports.yml
    secrets: inherit
    permissions:
      contents: write

  # 2) Jeux de données WFCD
  update_wfcd:
    name: 2) Update WFCD datasets
    uses: ./.github/workflows/update-wfcd.yml
    needs: [update_exports]
    secrets: inherit
    permissions:
      contents: write

  # 3) Overframe (pages + chunks) — non critique
  scrape_overframe:
    name: 3) Scrape Overframe (pages & chunks)
    uses: ./.github/workflows/scrape-overframe.yml
    needs: [update_exports, update_wfcd]
    secrets: inherit
    permissions:
      contents: write

  # 3b) Fetch WFStat weapons (après Overframe)
  fetch_wfstat_weapons:
    name: 3b) Fetch WFStat weapons
    uses: ./.github/workflows/fetch-wfstat-weapons.yml
    needs: [scrape_overframe]
    secrets: inherit
    permissions:
      contents: write

  # 4) Enrich mods (fusion DE+WFCD; consomme Overframe si dispo)
  enrich_mods:
    name: 4) Build enriched_mods
    uses: ./.github/workflows/enrich-mods.yml
    # ne dépend PAS de scrape_overframe pour ne pas bloquer si ça échoue
    needs: [update_exports, update_wfcd]
    secrets: inherit
    permissions:
      contents: write

  # 4b) Enrich weapons (après enrich_mods + fetch WFStat)
  enrich_weapons:
    name: 4b) Build enriched_weapons
    uses: ./.github/workflows/enrich-weapons.yml
    needs: [enrich_mods, fetch_wfstat_weapons]
    secrets: inherit
    permissions:
      contents: write

  # 5) Build reliques (DE + WFCD drops)
  build_relics:
    name: 5) Build enriched_relics
    uses: ./.github/workflows/build-relics.yml
    needs: [update_exports, update_wfcd]
    secrets: inherit
    permissions:
      contents: write

  # 6) Merge Warframes final
  build_merged_warframes:
    name: 6) Build merged_warframe.json
    uses: ./.github/workflows/build-merged-warfames.yml
    needs: [enrich_mods, build_relics, enrich_weapons]
    secrets: inherit
    permissions:
      contents: write