name: Overframe — Pages & Chunks

on:
  schedule:
    - cron: "17 3 * * *"    # scrape pages (quotidien)
    - cron: "13 4 * * 1"    # extract chunks (hebdo)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  pages_scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build page scraper
        working-directory: overframe-scraper
        run: go build -o scraper

      - name: Run page scraper (polite one-shot)
        working-directory: overframe-scraper
        env:
          BASE_URL: "https://overframe.gg/items/arsenal/%d"
          START_ID: "1"
          END_ID: "7468"        # ← requis pour le one-shot
          RATE_MS: "1000"
          JITTER_MS: "200"
        run: ./scraper

      - name: Prepare site data dir
        run: mkdir -p data/overframe

      - name: Copy small outputs (commit) + zip raw (artifact)
        run: |
          cp overframe-scraper/items.json data/overframe/OF_items.json
          cp overframe-scraper/items.csv  data/overframe/OF_items.csv
          cp overframe-scraper/index.csv  data/overframe/OF_index.csv
          cd overframe-scraper && zip -r ../overframe-raw-json.zip raw || true

      - name: Commit small outputs if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add data/overframe/OF_items.json data/overframe/OF_items.csv data/overframe/OF_index.csv
            git commit -m "chore(scrape): update items/index (no raw in git)"
            git push
          fi

      - name: Upload RAW artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: overframe-raw-json
          path: overframe-raw-json.zip

  chunk_extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build chunk extractor
        working-directory: overframe-scraper/chunks
        run: go build -o overframe-chunks

      - name: Run extractor (auto-discovery)
        working-directory: overframe-scraper/chunks
        env:
          OUT: "../../data/overframe"
        run: ./overframe-chunks -auto=true -out "$OUT"

      - name: Commit chunk JSON if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add data/overframe/overframe-*.json
            git commit -m "chore(chunks): refresh Overframe DB JSON"
            git push
          fi
