name: Update Official Wiki (Warframes Module → JSON + WFCD-like scrape)

on:
  schedule:
    - cron: "17 */12 * * *"   # 2×/jour, décalé
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: wiki-warframes-module
  cancel-in-progress: false

jobs:
  wiki:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Ensure folders
        run: |
          mkdir -p tools data/wiki/modules data/wiki/json

      # ---- DUMP complet du module Lua (facultatif mais utile) ----
      - name: Install Lua + Luarocks
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.3 liblua5.3-dev luarocks
          sudo luarocks install dkjson

      - name: Fetch Module:Warframes/data (robuste)
        run: |
          python3 tools/fetch_official_module.py \
            --title "Module:Warframes/data" \
            --out "data/wiki/modules/Module_Warframes_data.lua"

      - name: Evaluate Lua → JSON (full dump)
        run: |
          lua tools/eval_lua_to_json.lua \
            data/wiki/modules/Module_Warframes_data.lua \
            data/wiki/json/warframes.module.json

      # ---- PATCH npm : lockfile + install + run ----
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Ensure npm lockfile
        run: |
          if [ ! -f package-lock.json ]; then
            echo "No package-lock.json → generating one…"
            npm install --package-lock-only
          else
            echo "package-lock.json already present."
          fi

      - name: Commit lockfile if created
        run: |
          if git ls-files --others --exclude-standard | grep -q '^package-lock.json$'; then
            git add package-lock.json
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "chore: add package-lock.json"
            git push
          fi

      - name: Install deps
        run: npm ci || npm i

      - name: Run WFCD-like scraper (Subsumed/Progenitor)
        run: npm run scrape:wiki

      - name: Commit data if changed
        run: |
          git add -A data/wiki
          if git diff --cached --quiet; then
            echo "Aucun changement à committer."
          else
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "chore: update wiki data ($(date -u +'%Y-%m-%d %H:%M:%S UTC'))"
            git push
          fi