name: Update Official Wiki (Warframes → JSON)

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: wiki-scrape
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure folders
        run: mkdir -p data/wiki

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install (tools/wiki)
        working-directory: tools/wiki
        run: |
          npm ci --no-audit --fund=false || npm i --no-audit --fund=false

      # Lance le scraper (qui essaie action=raw d’abord)
      - name: Run official-wiki scraper (Warframes)
        working-directory: tools/wiki
        run: npm run scrape

      - name: Commit data if changed
        run: |
          git add -A data/wiki
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "chore(wiki): update Warframes module JSON ($(date -u +'%Y-%m-%d %H:%M:%S UTC'))"
            git push
          fi
