name: Update Official Wiki (Warframes → JSON)

on:
  schedule:
    - cron: "23 */12 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: wiki-warframes
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ensure folders
        run: |
          mkdir -p tools/wiki data/wiki

      # First pass: no cache, create lockfile inside tools/wiki
      - name: Setup Node (no cache)
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Ensure npm lockfile (tools/wiki)
        working-directory: tools/wiki
        run: |
          if [ ! -f package-lock.json ]; then
            echo "No lockfile in tools/wiki → generating…"
            npm install --package-lock-only --no-audit --fund=false
          else
            echo "Lockfile already present in tools/wiki."
          fi

      - name: Commit lockfile if created
        run: |
          if git ls-files --others --exclude-standard | grep -q '^tools/wiki/package-lock.json$'; then
            git add tools/wiki/package-lock.json
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "chore(wiki): add package-lock.json"
            git push
          fi

      # Second pass: with cache, now that lockfile exists
      - name: Setup Node (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: tools/wiki/package-lock.json

      - name: Install (tools/wiki)
        working-directory: tools/wiki
        run: npm ci --no-audit --fund=false || npm i --no-audit --fund=false

      - name: Run official-wiki scraper (Warframes)
        working-directory: tools/wiki
        run: npm run scrape

      - name: Commit data if changed
        run: |
          git add -A data/wiki
          if git diff --cached --quiet; then
            echo "Aucun changement à committer."
          else
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "chore(wiki): update warframes data ($(date -u +'%Y-%m-%d %H:%M:%S UTC'))"
            git push
          fi