name: Update WFCD datasets (strict build of upstream repos)

on:
  schedule:
    - cron: "15 */6 * * *"   # décalé vs tes autres jobs
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: warframe-wfcd-strict
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Ensure output folders
        run: |
          mkdir -p data/wfcd_items data/wfcd_drops

      # ----------- Build warframe-items (WFCD) tel quel -----------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Dépendances système requises par warframe-items (spritesheets, etc.)
      - name: Install system deps for warframe-items
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.3 liblua5.3-dev luarocks build-essential \
                                  libpng-dev zlib1g-dev jq

      - name: Clone WFCD/warframe-items
        run: |
          rm -rf tmp_wi
          git clone --depth=1 https://github.com/WFCD/warframe-items.git tmp_wi

      - name: Build warframe-items (upstream scripts)
        working-directory: tmp_wi
        run: |
          set -e
          npm ci
          # Le build upstream génère data/json/*.json
          npm run build
          ls -la data/json | head -n 50

      - name: Copy warframe-items outputs to repo
        run: |
          rsync -a tmp_wi/data/json/ ./data/wfcd_items/
          echo "✓ warframe-items JSON copied to data/wfcd_items/"

      # ----------- Build warframe-drop-data (WFCD) tel quel -----------
      - name: Clone WFCD/warframe-drop-data
        run: |
          rm -rf tmp_wdd
          git clone --depth=1 https://github.com/WFCD/warframe-drop-data.git tmp_wdd

      - name: Build warframe-drop-data (upstream scripts)
        working-directory: tmp_wdd
        run: |
          set -e
          npm ci
          # Upstream: le script principal génère le dossier data/ avec les JSON (incl. all.slim.json)
          node generateData.js
          ls -la data | head -n 50

      - name: Copy warframe-drop-data outputs to repo
        run: |
          rsync -a tmp_wdd/data/ ./data/wfcd_drops/
          echo "✓ warframe-drop-data JSON copied to data/wfcd_drops/"

      # ----------- Commit si changements -----------
      - name: Commit data if changed
        run: |
          git add -A data/
          if git diff --cached --quiet; then
            echo "Aucun changement à committer."
          else
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "chore: update WFCD datasets (strict upstream) ($(date -u +'%Y-%m-%d %H:%M:%S UTC'))"
            git push
          fi