name: Update Official Wiki – Warframes Module → JSON

on:
  schedule:
    - cron: "13 */12 * * *"   # 2x/jour
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: wiki-warframes-module
  cancel-in-progress: false

jobs:
  dump_module:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Ensure folders
        run: |
          mkdir -p tools data/wiki/modules data/wiki/json

      - name: Install Lua + Luarocks
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.3 liblua5.3-dev luarocks
          sudo luarocks install dkjson

      - name: Write tools/fetch_official_module.py
        run: |
          cat > tools/fetch_official_module.py <<'PY'
          import argparse, pathlib, sys, urllib.parse, urllib.request, xml.etree.ElementTree as ET

          BASE = "https://wiki.warframe.com"
          UA   = "Mozilla/5.0 (GitHub Actions; Cephalon-Wodan Module Fetcher)"

          def http_get(url, timeout=25):
            req = urllib.request.Request(url, headers={"User-Agent": UA})
            with urllib.request.urlopen(req, timeout=timeout) as r:
              return r.getcode(), r.read()

          def fetch_raw(title:str):
            q = urllib.parse.urlencode({"title": title, "action":"raw", "ctype":"text/plain"})
            url = f"{BASE}/w/index.php?{q}"
            try:
              code, data = http_get(url)
              if code == 200 and data: return data
            except Exception:
              pass
            return None

          def fetch_edit(title:str):
            q = urllib.parse.urlencode({"title": title, "action":"edit"})
            url = f"{BASE}/w/index.php?{q}"
            code, data = http_get(url)
            if code == 200 and data:
              # extrait le wikitext du textarea (fallback si raw bloqué)
              import re, html
              m = re.search(r'<textarea[^>]*id=["\']wpTextbox1["\'][^>]*>([\\s\\S]*?)</textarea>', data.decode('utf-8', 'replace'), re.I)
              if m:
                txt = html.unescape(m.group(1))
                return txt.encode('utf-8')
            return None

          def fetch_export(title:str):
            page = urllib.parse.quote(title, safe="")
            url = f"{BASE}/wiki/Special:Export/{page}?history=0&action=submit&templates=1"
            try:
              code, data = http_get(url)
              if code == 200 and data:
                root = ET.fromstring(data)
                ns = {"mw":"http://www.mediawiki.org/xml/export-0.10/"}
                text = root.find(".//mw:text", ns)
                if text is not None and text.text:
                  return text.text.encode("utf-8")
            except Exception:
              pass
            return None

          def main():
            ap = argparse.ArgumentParser()
            ap.add_argument("--title", required=True)  # e.g. Module:Warframes/data
            ap.add_argument("--out", required=True)    # path to .lua
            args = ap.parse_args()

            title = args.title
            out   = pathlib.Path(args.out)
            out.parent.mkdir(parents=True, exist_ok=True)

            data = fetch_raw(title) or fetch_edit(title) or fetch_export(title)
            if not data:
              print(f"[ERR] Unable to fetch {title}", file=sys.stderr)
              sys.exit(1)

            out.write_bytes(data)
            print(f"✓ Saved {title} -> {out} ({len(data)} bytes)")

          if __name__ == "__main__":
            main()
          PY

      - name: Write tools/eval_lua_to_json.lua
        run: |
          cat > tools/eval_lua_to_json.lua <<'LUA'
          -- usage: lua tools/eval_lua_to_json.lua <module.lua> <out.json>
          local in_path = arg[1]
          local out_path = arg[2] or (in_path .. ".json")

          local ok, dkjson = pcall(require, "dkjson")
          if not ok then
            io.stderr:write("dkjson not found (luarocks install dkjson)\n")
            os.exit(1)
          end

          local function sandbox_env()
            return {
              _G=_G,
              pairs=pairs, ipairs=ipairs, next=next,
              type=type, tostring=tostring, tonumber=tonumber,
              string=string, table=table, math=math,
            }
          end

          local function load_module_as_chunk(path)
            local f, err = loadfile(path, "t", sandbox_env())
            if not f then return nil, err end
            return f
          end

          local chunk, err = load_module_as_chunk(in_path)
          if not chunk then
            io.stderr:write("load error: " .. tostring(err) .. "\n")
            os.exit(2)
          end

          local ok2, res = pcall(chunk)
          if not ok2 then
            io.stderr:write("run error: " .. tostring(res) .. "\n")
            os.exit(3)
          end

          if type(res) ~= "table" then
            io.stderr:write("module did not return a table; skipping\n")
            os.exit(4)
          end

          local json = dkjson.encode(res, { indent = false }) -- JSON “brut” complet
          local f = assert(io.open(out_path, "w"))
          f:write(json)
          f:close()
          print("✓ Wrote JSON:", out_path)
          LUA

      - name: Fetch Module:Warframes/data (official wiki)
        run: |
          python3 tools/fetch_official_module.py \
            --title "Module:Warframes/data" \
            --out "data/wiki/modules/Module_Warframes_data.lua"

      - name: Evaluate → JSON (full dataset)
        run: |
          lua tools/eval_lua_to_json.lua \
            data/wiki/modules/Module_Warframes_data.lua \
            data/wiki/json/warframes.module.json

      - name: Commit if changed
        run: |
          git add -A data/wiki/modules/Module_Warframes_data.lua data/wiki/json/warframes.module.json
          if git diff --cached --quiet; then
            echo "Aucun changement à committer."
          else
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "chore: update Warframes module → JSON ($(date -u +'%Y-%m-%d %H:%M:%S UTC'))"
            git push
          fi
