name: Update Official Wiki (Warframes → JSON)

on:
  schedule:
    - cron: "23 */12 * * *"   # 2×/jour, décallé pour éviter les collisions
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: wiki-warframes
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 0) Checkout
      - name: Checkout repo
        uses: actions/checkout@v4

      # 1) Dossiers de sortie
      - name: Ensure output folders
        run: |
          mkdir -p tools data/wiki

      # 2) Node + cache
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      # 3) Générer un package-lock.json si absent (et le committer)
      - name: Ensure npm lockfile
        run: |
          if [ ! -f package-lock.json ]; then
            echo "No package-lock.json → generating one…"
            npm install --package-lock-only
          else
            echo "package-lock.json already present."
          fi

      - name: Commit lockfile if created
        run: |
          if git ls-files --others --exclude-standard | grep -q '^package-lock.json$'; then
            git add package-lock.json
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "chore: add package-lock.json"
            git push
          fi

      # 4) Installer les dépendances
      - name: Install deps
        run: npm ci || npm i

      # 5) Lancer le scraper Wiki officiel (Module:Warframes/data → JSON)
      - name: Run official-wiki scraper (Warframes)
        run: npm run scrape:wiki

      # 6) Commit des données si modifiées
      - name: Commit data if changed
        run: |
          git add -A data/wiki
          if git diff --cached --quiet; then
            echo "Aucun changement à committer."
          else
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "chore: update wiki warframes ($(date -u +'%Y-%m-%d %H:%M:%S UTC'))"
            git push
          fi