name: Worldstate cache (all platforms)

on:
  schedule:
    # Rafraîchit toutes les 5 minutes (plus fréquent n'est pas garanti par Actions)
    - cron: "*/5 * * * *"
  workflow_dispatch: {}        # bouton « Run workflow »
  repository_dispatch:
    types: [worldstate-refresh] # optionnel : déclenchement externe

concurrency:
  group: worldstate-cache
  cancel-in-progress: true

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build JSON (all platforms)
        run: |
          mkdir -p data
          node tools/worldstate_custom_parser.mjs > data/worldstate_all.json
          # petite estampille
          node -e "const fs=require('fs');const p='data/worldstate_all.json';const j=JSON.parse(fs.readFileSync(p,'utf8'));j._meta=j._meta||{};j._meta.ciUpdatedAt=new Date().toISOString();fs.writeFileSync(p,JSON.stringify(j,null,2));"

      - name: Commit changes (if any)
        run: |
          if [[ -n "$(git status --porcelain data/worldstate_all.json)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/worldstate_all.json
            git commit -m "ci(worldstate): refresh cache (all platforms)"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: worldstate_all.json
          path: data/worldstate_all.json
          retention-days: 3
